// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DH_Auto_Test_Exercise.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("DH Features to test UI Testing website")]
    public partial class DHFeaturesToTestUITestingWebsiteFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Home page features.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DH Features to test UI Testing website", "In order to test the DH UI Testing website\r\nAs a user\r\nI want to verify page elem" +
                    "ents and functionalities exist and work as expected", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The title UI Testing is visible regardless of the page being visited")]
        [NUnit.Framework.CategoryAttribute("moderate")]
        [NUnit.Framework.CategoryAttribute("uivisible")]
        [NUnit.Framework.TestCaseAttribute("form", null)]
        [NUnit.Framework.TestCaseAttribute("home", null)]
        [NUnit.Framework.TestCaseAttribute("error", null)]
        public virtual void TheTitleUITestingIsVisibleRegardlessOfThePageBeingVisited(string button, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "moderate",
                    "uivisible"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The title UI Testing is visible regardless of the page being visited", null, @__tags);
#line 12
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 14
testRunner.Given("I am on the DH UI Testing home website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
testRunner.And("the title of the site UI Testing is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
testRunner.When(string.Format("I click on button {0}", button), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
testRunner.Then("the title of the site UI Testing is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The DH logo is visible regardless of the page being visited")]
        [NUnit.Framework.CategoryAttribute("moderate")]
        [NUnit.Framework.CategoryAttribute("logovisible")]
        [NUnit.Framework.TestCaseAttribute("form", null)]
        [NUnit.Framework.TestCaseAttribute("home", null)]
        [NUnit.Framework.TestCaseAttribute("error", null)]
        public virtual void TheDHLogoIsVisibleRegardlessOfThePageBeingVisited(string button, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "moderate",
                    "logovisible"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The DH logo is visible regardless of the page being visited", null, @__tags);
#line 30
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 32
testRunner.Given("I am on the DH UI Testing home website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
testRunner.And("the DH logo is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
testRunner.When(string.Format("I click on button {0}", button), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
testRunner.Then("the DH logo is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Clicking on home \\ form button renders such button active")]
        [NUnit.Framework.CategoryAttribute("low")]
        [NUnit.Framework.CategoryAttribute("homeactive")]
        [NUnit.Framework.TestCaseAttribute("form", null)]
        [NUnit.Framework.TestCaseAttribute("home", null)]
        public virtual void ClickingOnHomeFormButtonRendersSuchButtonActive(string button, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "low",
                    "homeactive"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Clicking on home \\ form button renders such button active", null, @__tags);
#line 48
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 50
testRunner.Given("I am on the DH UI Testing home website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 51
testRunner.When(string.Format("I click on button {0}", button), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
testRunner.Then("home page is active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Clicking on home button leads to home page, clicking on form button leads to Form" +
            " page and clicking on UI Testing site title leads to home page")]
        [NUnit.Framework.CategoryAttribute("high")]
        [NUnit.Framework.CategoryAttribute("buttonleads")]
        [NUnit.Framework.TestCaseAttribute("form", null)]
        [NUnit.Framework.TestCaseAttribute("home", null)]
        [NUnit.Framework.TestCaseAttribute("site", null)]
        public virtual void ClickingOnHomeButtonLeadsToHomePageClickingOnFormButtonLeadsToFormPageAndClickingOnUITestingSiteTitleLeadsToHomePage(string site_Type, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "high",
                    "buttonleads"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Clicking on home button leads to home page, clicking on form button leads to Form" +
                    " page and clicking on UI Testing site title leads to home page", null, @__tags);
#line 65
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 67
testRunner.Given("I am on the DH UI Testing home website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 68
testRunner.When(string.Format("I click on button {0}", site_Type), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 69
testRunner.Then(string.Format("I am on {0} page", site_Type), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Home page features the text \"Welcome to the Docler Holding QA Department\" in h1")]
        [NUnit.Framework.CategoryAttribute("low")]
        [NUnit.Framework.CategoryAttribute("texth1home")]
        public virtual void HomePageFeaturesTheTextWelcomeToTheDoclerHoldingQADepartmentInH1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Home page features the text \"Welcome to the Docler Holding QA Department\" in h1", null, new string[] {
                        "low",
                        "texth1home"});
#line 82
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 84
testRunner.Given("I am on the DH UI Testing home website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
testRunner.When("I click on button \"home\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 86
testRunner.Then("the text in h1 should read \"Welcome to the Docler Holding QA Department\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Home page features the text \"This site is dedicated to perform some exercises and" +
            " demonstrate automated web testing.\" in p")]
        [NUnit.Framework.CategoryAttribute("low")]
        [NUnit.Framework.CategoryAttribute("textphome")]
        public virtual void HomePageFeaturesTheTextThisSiteIsDedicatedToPerformSomeExercisesAndDemonstrateAutomatedWebTesting_InP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Home page features the text \"This site is dedicated to perform some exercises and" +
                    " demonstrate automated web testing.\" in p", null, new string[] {
                        "low",
                        "textphome"});
#line 92
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 94
testRunner.Given("I am on the DH UI Testing home website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 95
testRunner.When("I click on button \"home\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 96
testRunner.Then("the text in p should read \"This site is dedicated to perform some exercises and d" +
                    "emonstrate automated web testing.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check the input box and the input button are visible")]
        [NUnit.Framework.CategoryAttribute("high")]
        [NUnit.Framework.CategoryAttribute("elementsform")]
        public virtual void CheckTheInputBoxAndTheInputButtonAreVisible()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the input box and the input button are visible", null, new string[] {
                        "high",
                        "elementsform"});
#line 102
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 104
testRunner.Given("I am on the DH UI Testing home website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 105
testRunner.When("I click on button \"form\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 106
testRunner.Then("the input box is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 107
testRunner.And("the input button is visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Input a value in home field and see submission leads to Hello page")]
        [NUnit.Framework.CategoryAttribute("high")]
        [NUnit.Framework.CategoryAttribute("inputform")]
        [NUnit.Framework.TestCaseAttribute("World", null)]
        public virtual void InputAValueInHomeFieldAndSeeSubmissionLeadsToHelloPage(string value, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "high",
                    "inputform"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Input a value in home field and see submission leads to Hello page", null, @__tags);
#line 113
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 115
testRunner.Given("I am on the DH UI Testing home website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 116
testRunner.When("I click on button \"form\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 117
testRunner.And(string.Format("I enter value \"{0}\" in the input box", value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
testRunner.And("I submit the form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
testRunner.Then(string.Format("I check the hello page with {0} is displayed", value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Clicking on error tab leads to error page 404")]
        [NUnit.Framework.CategoryAttribute("high")]
        [NUnit.Framework.CategoryAttribute("errorpage")]
        public virtual void ClickingOnErrorTabLeadsToErrorPage404()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Clicking on error tab leads to error page 404", null, new string[] {
                        "high",
                        "errorpage"});
#line 130
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 132
testRunner.Given("I am on the DH UI Testing home website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 133
testRunner.When("I click on button \"error\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 134
testRunner.Then("I check a 404 error is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
